name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - run: |
          npm config ls
          cat /home/runner/work/_temp/.npmrc
        continue-on-error: true

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org

      - run: |
          npm config ls
          cat /home/runner/work/_temp/.npmrc
        continue-on-error: true

      - name: Install dependencies and publish
        run: |
          npm ci
          npm whoami
          npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}